/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false` (hash: 8f08941b6c0190ee45eabdb619e979d8)
interface __BaseEnv_Env {
	PRESS_API_CACHE: KVNamespace;
	DB: D1Database;
	AI: Ai;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
